opency service moved to loop is currently pulling fromSQS but need to play with the format of the messages to get it to work properly.
current error is:
Traceback (most recent call last):
  File "/home/craigb/Documents/GitHub/CAB432_cloudProject/opencvservice/vehicle_count.py", line 297, in <module>
    process_message(message)
  File "/home/craigb/Documents/GitHub/CAB432_cloudProject/opencvservice/vehicle_count.py", line 273, in process_message
    id = message['MessageAttributes']['carmeraid']['StringValue']
         ~~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'MessageAttributes'